# overriding settings for local/no-vault testing 
services:
  bot:
    environment:
      VAULT_ADDR: ""
      DISCORD_BOT_TOKEN_FILE: ""
      NEXTCLOUD_USER_FILE: ""
      NEXTCLOUD_PASS_FILE: ""
      SIGNAL_SENDER_FILE: ""
      VAULT_BOT_TOKEN_FILE: ""
      DELEGATIONS_JSON_FILE: ""
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      NEXTCLOUD_USER: ${NEXTCLOUD_USER}
      NEXTCLOUD_PASS: ${NEXTCLOUD_PASS}
      SIGNAL_SENDER: ${SIGNAL_SENDER}
      DELEGATIONS_JSON: ${DELEGATIONS_JSON}
    depends_on:
      - signal-api

  poller:
    command: /usr/local/bin/supercronic -debug /app/poller.crontab
    environment:
      DISCORD_BOT_TOKEN_FILE: ""
      NEXTCLOUD_USER_FILE: ""
      NEXTCLOUD_PASS_FILE: ""
      SIGNAL_SENDER_FILE: ""
      DELEGATIONS_JSON_FILE: ""
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      NEXTCLOUD_USER: ${NEXTCLOUD_USER}
      NEXTCLOUD_PASS: ${NEXTCLOUD_PASS}
      SIGNAL_SENDER: ${SIGNAL_SENDER}
      DELEGATIONS_JSON: ${DELEGATIONS_JSON}
    depends_on:
      - signal-api