services:
  # local vault testing; remove
  vault:
    image: hashicorp/vault:1.18
    container_name: nc-vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    command: vault server -dev
    restart: unless-stopped

  vault-agent:
    image: hashicorp/vault:1.18
    container_name: nc-vault-agent
    command: vault agent -config=/vault-agent/agent.hcl
    cap_add: [IPC_LOCK] # suppress warning
    environment:
      VAULT_ADDR: http://vault:8200 # local; fine for server vers
    user: "0:0" # local; remove
    depends_on: # local; remove
      - vault
    volumes:
      - ./vault-agent:/vault-agent:ro
      - secrets-vol:/shared-secrets
    restart: unless-stopped

  signal-api:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: nc-signal-api
    environment:
      MODE: "native"
    volumes:
      - ./signal-data:/home/.local/share/signal-cli
    restart: unless-stopped

  bot:
    build: .
    container_name: nc-discord-bot
    command: python -u dc_bot.py
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      # TODO: local
      VAULT_ADDR: http://vault:8200
      DISCORD_BOT_TOKEN_FILE: /run/secrets/discord_bot_token
      NEXTCLOUD_USER_FILE: /run/secrets/nextcloud_user
      NEXTCLOUD_PASS_FILE: /run/secrets/nextcloud_pass
      SIGNAL_SENDER_FILE: /run/secrets/signal_sender
      # USER_MAP_DC_FILE: /run/secrets/user_map_dc
      # USER_MAP_SIGNAL_FILE: /run/secrets/user_map_signal
      # DELEGATOR_DISCORD_ID_FILE: /run/secrets/delegator_discord_id
      VAULT_BOT_TOKEN_FILE: /run/secrets/vault_admin_token
      DELEGATIONS_JSON_FILE: /run/secrets/delegations_json
    depends_on:
      - vault-agent
      - signal-api
    volumes:
      - ./data:/app/data
      - secrets-vol:/run/secrets:ro
    restart: unless-stopped

  poller:
    build: .
    container_name: nc-discord-poller
    command: sh -c 'until [ -s /run/secrets/discord_bot_token ]; do echo waiting for vault secrets; sleep 1; done; /usr/local/bin/supercronic -debug /app/poller.crontab'
    env_file:
      - .env
    environment:
      DATA_DIR: /app/data
      DISCORD_BOT_TOKEN_FILE: /run/secrets/discord_bot_token
      NEXTCLOUD_USER_FILE: /run/secrets/nextcloud_user
      NEXTCLOUD_PASS_FILE: /run/secrets/nextcloud_pass
      SIGNAL_SENDER_FILE: /run/secrets/signal_sender
      # USER_MAP_DC_FILE: /run/secrets/user_map_dc
      # USER_MAP_SIGNAL_FILE: /run/secrets/user_map_signal
      # DELEGATOR_DISCORD_ID_FILE: /run/secrets/delegator_discord_id
      DELEGATIONS_JSON_FILE: /run/secrets/delegations_json
    depends_on:
      - vault-agent
      - signal-api
    volumes:
      - ./data:/app/data
      - secrets-vol:/run/secrets:ro
    restart: unless-stopped

volumes:
  secrets-vol: